


name: R Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 17 * * *'  # Adjusted to run at 17:30 UTC

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: 4.3.2

    - name: Install R packages
      run: |
        R -e "install.packages(c('gargle', 'googleAuthR', 'jsonlite', 'knitr', 'dplyr', 'blastula', 'Microsoft365R', 'huxtable', 'tidyverse', 'httr2', 'emayili', 'rmarkdown', 'csodata', 'xts', 'calendar', 'DescTools', 'httr', 'huxtable', 'tidyverse', 'httr2', 'splitstackshape', 'pdftools', 'rvest', 'lubridate'), dependencies=TRUE)"

    - name: Run R script
      run: Rscript analysis.R

    - name: Commit changes
      run: |
        git config --local user.email "mflanagan202@gmail.com"
        git config --local user.name "mflanagan201"
        git add .
        git commit -m "Update Google Calendar events [skip ci]"
        git push
