name: R Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 17 * * *'  # Adjusted to run at 17:30 UTC

jobs:
  run_rscript:
    runs-on: ubuntu-latest

    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_CALENDAR_ID: ${{ secrets.GOOGLE_CALENDAR_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        R -e 'install.packages(c("httr", "gargle", "googleAuthR", "jsonlite", "knitr", "dplyr", "huxtable", "tidyverse", "httr2", "rmarkdown", "csodata", "xts", "calendar", "DescTools", "splitstackshape", "pdftools", "rvest", "lubridate"), repos="http://cran.rstudio.com/")'

    - name: Run R script
      run:  Rscript_analysis.R

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update Google Calendar events [skip ci]"
        git push
